// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugVU7PoJRHvi09Vw9hFs0XWkJT2uivRk',
    appId: '1:832268093680:web:4c5d6a8406d180eca89a35',
    messagingSenderId: '832268093680',
    projectId: 'messtag-001',
    authDomain: 'messtag-001.firebaseapp.com',
    storageBucket: 'messtag-001.appspot.com',
    measurementId: 'G-MDW83GZTEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2oF5lCEADuYVoO84MfGnBQpAcfQzKvC0',
    appId: '1:832268093680:android:6304dd444d330712a89a35',
    messagingSenderId: '832268093680',
    projectId: 'messtag-001',
    storageBucket: 'messtag-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Kn_hbz92fl_RVmIs0Rh6k4Yv-3CQ20w',
    appId: '1:832268093680:ios:3f97b25a03f1312fa89a35',
    messagingSenderId: '832268093680',
    projectId: 'messtag-001',
    storageBucket: 'messtag-001.appspot.com',
    iosClientId: '832268093680-l9sqdb6hm801cn17afa52p0qma2pfkba.apps.googleusercontent.com',
    iosBundleId: 'com.kce.messTag',
  );
}
